// Copyright (C) 2024 Radzivon Bartoshyk
//
// This file belongs to sparkyuv project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef YUV_INCLUDE_SPARKYUV_YCGCOR_H_
#define YUV_INCLUDE_SPARKYUV_YCGCOR_H_
namespace sparkyuv {
#define PIXEL_TO_YCGCOR_H(T, PixelType, bit, yuvname) \
void PixelType##bit##To##yuvname##P##bit(const T * src, const uint32_t srcStride,\
                    const uint32_t width, const uint32_t height,\
                    uint16_t * yPlane, const uint32_t yStride,  \
                    uint16_t * uPlane, const uint32_t uStride,\
                    uint16_t * vPlane, const uint32_t vStride, \
                    const SparkYuvYCgCoRType rType);

PIXEL_TO_YCGCOR_H(uint16_t, RGBA, 10, YCgCoR444)
PIXEL_TO_YCGCOR_H(uint16_t, RGB, 10, YCgCoR444)
#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCGCOR_H(uint16_t, BGRA, 10, YCgCoR444)
PIXEL_TO_YCGCOR_H(uint16_t, ABGR, 10, YCgCoR444)
PIXEL_TO_YCGCOR_H(uint16_t, ARGB, 10, YCgCoR444)
PIXEL_TO_YCGCOR_H(uint16_t, BGR, 10, YCgCoR444)
#endif

PIXEL_TO_YCGCOR_H(uint16_t, RGBA, 12, YCgCoR444)
PIXEL_TO_YCGCOR_H(uint16_t, RGB, 12, YCgCoR444)
#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCGCOR_H(uint16_t, BGRA, 12, YCgCoR444)
PIXEL_TO_YCGCOR_H(uint16_t, ABGR, 12, YCgCoR444)
PIXEL_TO_YCGCOR_H(uint16_t, ARGB, 12, YCgCoR444)
PIXEL_TO_YCGCOR_H(uint16_t, BGR, 12, YCgCoR444)
#endif


PIXEL_TO_YCGCOR_H(uint16_t, RGBA, 10, YCgCoR422)
PIXEL_TO_YCGCOR_H(uint16_t, RGB, 10, YCgCoR422)
#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCGCOR_H(uint16_t, BGRA, 10, YCgCoR422)
PIXEL_TO_YCGCOR_H(uint16_t, ABGR, 10, YCgCoR422)
PIXEL_TO_YCGCOR_H(uint16_t, ARGB, 10, YCgCoR422)
PIXEL_TO_YCGCOR_H(uint16_t, BGR, 10, YCgCoR422)
#endif

PIXEL_TO_YCGCOR_H(uint16_t, RGBA, 12, YCgCoR422)
PIXEL_TO_YCGCOR_H(uint16_t, RGB, 12, YCgCoR422)
#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCGCOR_H(uint16_t, BGRA, 12, YCgCoR422)
PIXEL_TO_YCGCOR_H(uint16_t, ABGR, 12, YCgCoR422)
PIXEL_TO_YCGCOR_H(uint16_t, ARGB, 12, YCgCoR422)
PIXEL_TO_YCGCOR_H(uint16_t, BGR, 12, YCgCoR422)
#endif

PIXEL_TO_YCGCOR_H(uint16_t, RGBA, 10, YCgCoR420)
PIXEL_TO_YCGCOR_H(uint16_t, RGB, 10, YCgCoR420)
#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCGCOR_H(uint16_t, BGRA, 10, YCgCoR420)
PIXEL_TO_YCGCOR_H(uint16_t, ABGR, 10, YCgCoR420)
PIXEL_TO_YCGCOR_H(uint16_t, ARGB, 10, YCgCoR420)
PIXEL_TO_YCGCOR_H(uint16_t, BGR, 10, YCgCoR420)
#endif

PIXEL_TO_YCGCOR_H(uint16_t, RGBA, 12, YCgCoR420)
PIXEL_TO_YCGCOR_H(uint16_t, RGB, 12, YCgCoR420)
#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCGCOR_H(uint16_t, BGRA, 12, YCgCoR420)
PIXEL_TO_YCGCOR_H(uint16_t, ABGR, 12, YCgCoR420)
PIXEL_TO_YCGCOR_H(uint16_t, ARGB, 12, YCgCoR420)
PIXEL_TO_YCGCOR_H(uint16_t, BGR, 12, YCgCoR420)
#endif

PIXEL_TO_YCGCOR_H(uint8_t, RGBA, 8, YCgCoR420)
PIXEL_TO_YCGCOR_H(uint8_t, RGB, 8, YCgCoR420)
#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCGCOR_H(uint8_t, BGRA, 8, YCgCoR420)
PIXEL_TO_YCGCOR_H(uint8_t, ABGR, 8, YCgCoR420)
PIXEL_TO_YCGCOR_H(uint8_t, ARGB, 8, YCgCoR420)
PIXEL_TO_YCGCOR_H(uint8_t, BGR, 8, YCgCoR420)
#endif

PIXEL_TO_YCGCOR_H(uint8_t, RGBA, 8, YCgCoR422)
PIXEL_TO_YCGCOR_H(uint8_t, RGB, 8, YCgCoR422)
#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCGCOR_H(uint8_t, BGRA, 8, YCgCoR422)
PIXEL_TO_YCGCOR_H(uint8_t, ABGR, 8, YCgCoR422)
PIXEL_TO_YCGCOR_H(uint8_t, ARGB, 8, YCgCoR422)
PIXEL_TO_YCGCOR_H(uint8_t, BGR, 8, YCgCoR422)
#endif

PIXEL_TO_YCGCOR_H(uint8_t, RGBA, 8, YCgCoR444)
PIXEL_TO_YCGCOR_H(uint8_t, RGB, 8, YCgCoR444)
#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCGCOR_H(uint8_t, BGRA, 8, YCgCoR444)
PIXEL_TO_YCGCOR_H(uint8_t, ABGR, 8, YCgCoR444)
PIXEL_TO_YCGCOR_H(uint8_t, ARGB, 8, YCgCoR444)
PIXEL_TO_YCGCOR_H(uint8_t, BGR, 8, YCgCoR444)
#endif

#undef PIXEL_TO_YCGCOR_H

#define YCGCOR_TO_PX_DECLARATION_H(T, pixel, bit, yuv) \
    void yuv##P##bit##To##pixel##bit(T * src, const uint32_t srcStride,\
                                             const uint32_t width, const uint32_t height,\
                                             const uint16_t * yPlane, const uint32_t yStride,\
                                             const uint16_t * uPlane, const uint32_t uStride,\
                                             const uint16_t * vPlane, const uint32_t vStride,\
                                             const SparkYuvYCgCoRType rType);

YCGCOR_TO_PX_DECLARATION_H(uint16_t, RGBA, 10, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, RGB, 10, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, RGBA, 10, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, RGB, 10, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, RGBA, 10, YCgCoR420)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, RGB, 10, YCgCoR420)

#if SPARKYUV_FULL_CHANNELS
YCGCOR_TO_PX_DECLARATION_H(uint16_t, BGRA, 10, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, ABGR, 10, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, ARGB, 10, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, BGR, 10, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, BGRA, 10, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, ABGR, 10, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, ARGB, 10, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, BGR, 10, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, BGRA, 10, YCgCoR420)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, ABGR, 10, YCgCoR420)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, ARGB, 10, YCgCoR420)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, BGR, 10, YCgCoR420)
#endif

YCGCOR_TO_PX_DECLARATION_H(uint8_t, RGBA, 8, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, RGB, 8, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, RGBA, 8, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, RGB, 8, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, RGBA, 8, YCgCoR420)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, RGB, 8, YCgCoR420)

#if SPARKYUV_FULL_CHANNELS
YCGCOR_TO_PX_DECLARATION_H(uint8_t, BGRA, 8, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, ABGR, 8, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, ARGB, 8, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, BGR, 8, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, BGRA, 8, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, ABGR, 8, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, ARGB, 8, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, BGR, 8, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, BGRA, 8, YCgCoR420)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, ABGR, 8, YCgCoR420)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, ARGB, 8, YCgCoR420)
YCGCOR_TO_PX_DECLARATION_H(uint8_t, BGR, 8, YCgCoR420)
#endif

YCGCOR_TO_PX_DECLARATION_H(uint16_t, RGBA, 12, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, RGB, 12, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, RGBA, 12, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, RGB, 12, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, RGBA, 12, YCgCoR420)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, RGB, 12, YCgCoR420)

#if SPARKYUV_FULL_CHANNELS
YCGCOR_TO_PX_DECLARATION_H(uint16_t, BGRA, 12, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, ABGR, 12, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, ARGB, 12, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, BGR, 12, YCgCoR444)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, BGRA, 12, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, ABGR, 12, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, ARGB, 12, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, BGR, 12, YCgCoR422)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, BGRA, 12, YCgCoR420)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, ABGR, 12, YCgCoR420)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, ARGB, 12, YCgCoR420)
YCGCOR_TO_PX_DECLARATION_H(uint16_t, BGR, 12, YCgCoR420)
#endif

#undef YCGCOR_TO_PX_DECLARATION_H

}
#endif //YUV_INCLUDE_SPARKYUV_YCGCOR_H_
