// Copyright (C) 2024 Radzivon Bartoshyk
//
// This file belongs to sparkyuv project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "sparkyuv.h"

#undef HWY_TARGET_INCLUDE
#define HWY_TARGET_INCLUDE "src/YcCbcCrc.cpp"

#include "hwy/foreach_target.h"
#include "hwy/highway.h"
#include "yuv-inl.h"
#include "YcCbcCrc-inl.h"

#if HWY_ONCE
namespace sparkyuv {
#define DECLARE_PX_TO_YCCBCCRC_HWY(pixel, bit, yuv) HWY_EXPORT(pixel##bit##To##yuv##P##bit##HWY);

DECLARE_PX_TO_YCCBCCRC_HWY(RGBA, 10, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(RGB, 10, YcCbcCrc444)

DECLARE_PX_TO_YCCBCCRC_HWY(RGBA, 12, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(RGB, 12, YcCbcCrc444)

DECLARE_PX_TO_YCCBCCRC_HWY(RGBA, 10, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(RGB, 10, YcCbcCrc422)

DECLARE_PX_TO_YCCBCCRC_HWY(RGBA, 12, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(RGB, 12, YcCbcCrc422)

DECLARE_PX_TO_YCCBCCRC_HWY(RGBA, 10, YcCbcCrc420)
DECLARE_PX_TO_YCCBCCRC_HWY(RGB, 10, YcCbcCrc420)

DECLARE_PX_TO_YCCBCCRC_HWY(RGBA, 12, YcCbcCrc420)
DECLARE_PX_TO_YCCBCCRC_HWY(RGB, 12, YcCbcCrc420)

DECLARE_PX_TO_YCCBCCRC_HWY(RGBA, 8, YcCbcCrc420)
DECLARE_PX_TO_YCCBCCRC_HWY(RGB, 8, YcCbcCrc420)

DECLARE_PX_TO_YCCBCCRC_HWY(RGBA, 8, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(RGB, 8, YcCbcCrc422)

DECLARE_PX_TO_YCCBCCRC_HWY(RGBA, 8, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(RGB, 8, YcCbcCrc444)

#if SPARKYUV_FULL_CHANNELS
DECLARE_PX_TO_YCCBCCRC_HWY(BGRA, 10, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(ABGR, 10, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(ARGB, 10, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(BGR, 10, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(BGRA, 10, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(ABGR, 10, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(ARGB, 10, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(BGR, 10, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(BGRA, 10, YcCbcCrc420)
DECLARE_PX_TO_YCCBCCRC_HWY(ABGR, 10, YcCbcCrc420)
DECLARE_PX_TO_YCCBCCRC_HWY(ARGB, 10, YcCbcCrc420)
DECLARE_PX_TO_YCCBCCRC_HWY(BGR, 10, YcCbcCrc420)
#endif

#if SPARKYUV_FULL_CHANNELS
DECLARE_PX_TO_YCCBCCRC_HWY(BGRA, 8, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(ABGR, 8, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(ARGB, 8, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(BGR, 8, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(BGRA, 8, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(ABGR, 8, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(ARGB, 8, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(BGR, 8, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(BGRA, 8, YcCbcCrc420)
DECLARE_PX_TO_YCCBCCRC_HWY(ABGR, 8, YcCbcCrc420)
DECLARE_PX_TO_YCCBCCRC_HWY(ARGB, 8, YcCbcCrc420)
DECLARE_PX_TO_YCCBCCRC_HWY(BGR, 8, YcCbcCrc420)
#endif

#if SPARKYUV_FULL_CHANNELS
DECLARE_PX_TO_YCCBCCRC_HWY(BGRA, 12, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(ABGR, 12, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(ARGB, 12, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(BGR, 12, YcCbcCrc444)
DECLARE_PX_TO_YCCBCCRC_HWY(BGRA, 12, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(ABGR, 12, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(ARGB, 12, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(BGR, 12, YcCbcCrc422)
DECLARE_PX_TO_YCCBCCRC_HWY(BGRA, 12, YcCbcCrc420)
DECLARE_PX_TO_YCCBCCRC_HWY(ABGR, 12, YcCbcCrc420)
DECLARE_PX_TO_YCCBCCRC_HWY(ARGB, 12, YcCbcCrc420)
DECLARE_PX_TO_YCCBCCRC_HWY(BGR, 12, YcCbcCrc420)
#endif

#undef DECLARE_PX_TO_YCCBCCRC_HWY

#define PIXEL_TO_YCCBCCRC_E(T, PixelType, bit, yuvname) \
void PixelType##bit##To##yuvname##P##bit(const T *SPARKYUV_RESTRICT src, const uint32_t srcStride,\
                    const uint32_t width, const uint32_t height,                                 \
                    T *SPARKYUV_RESTRICT yPlane, const uint32_t yStride,                         \
                    T *SPARKYUV_RESTRICT uPlane, const uint32_t uStride,                         \
                    T *SPARKYUV_RESTRICT vPlane, const uint32_t vStride,                         \
                    const float kr, const float kb,                                              \
                    const SparkYuvColorRange colorRange,                                         \
                    const SparkYuvTransferFunction transferFunction) { \
      HWY_DYNAMIC_DISPATCH(PixelType##bit##To##yuvname##P##bit##HWY)(src, srcStride, width, height, \
          yPlane, yStride, uPlane, uStride, vPlane, vStride, kr, kb, colorRange, transferFunction);\
    }

PIXEL_TO_YCCBCCRC_E(uint16_t, RGBA, 10, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint16_t, RGB, 10, YcCbcCrc444)

PIXEL_TO_YCCBCCRC_E(uint16_t, RGBA, 12, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint16_t, RGB, 12, YcCbcCrc444)

PIXEL_TO_YCCBCCRC_E(uint16_t, RGBA, 10, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint16_t, RGB, 10, YcCbcCrc422)

PIXEL_TO_YCCBCCRC_E(uint16_t, RGBA, 12, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint16_t, RGB, 12, YcCbcCrc422)

PIXEL_TO_YCCBCCRC_E(uint16_t, RGBA, 10, YcCbcCrc420)
PIXEL_TO_YCCBCCRC_E(uint16_t, RGB, 10, YcCbcCrc420)

PIXEL_TO_YCCBCCRC_E(uint16_t, RGBA, 12, YcCbcCrc420)
PIXEL_TO_YCCBCCRC_E(uint16_t, RGB, 12, YcCbcCrc420)

PIXEL_TO_YCCBCCRC_E(uint8_t, RGBA, 8, YcCbcCrc420)
PIXEL_TO_YCCBCCRC_E(uint8_t, RGB, 8, YcCbcCrc420)

PIXEL_TO_YCCBCCRC_E(uint8_t, RGBA, 8, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint8_t, RGB, 8, YcCbcCrc422)

PIXEL_TO_YCCBCCRC_E(uint8_t, RGBA, 8, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint8_t, RGB, 8, YcCbcCrc444)

#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCCBCCRC_E(uint16_t, BGRA, 10, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint16_t, ABGR, 10, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint16_t, ARGB, 10, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint16_t, BGR, 10, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint16_t, BGRA, 10, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint16_t, ABGR, 10, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint16_t, ARGB, 10, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint16_t, BGR, 10, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint16_t, BGRA, 10, YcCbcCrc420)
PIXEL_TO_YCCBCCRC_E(uint16_t, ABGR, 10, YcCbcCrc420)
PIXEL_TO_YCCBCCRC_E(uint16_t, ARGB, 10, YcCbcCrc420)
PIXEL_TO_YCCBCCRC_E(uint16_t, BGR, 10, YcCbcCrc420)
#endif

#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCCBCCRC_E(uint8_t, BGRA, 8, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint8_t, ABGR, 8, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint8_t, ARGB, 8, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint8_t, BGR, 8, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint8_t, BGRA, 8, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint8_t, ABGR, 8, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint8_t, ARGB, 8, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint8_t, BGR, 8, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint8_t, BGRA, 8, YcCbcCrc420)
PIXEL_TO_YCCBCCRC_E(uint8_t, ABGR, 8, YcCbcCrc420)
PIXEL_TO_YCCBCCRC_E(uint8_t, ARGB, 8, YcCbcCrc420)
PIXEL_TO_YCCBCCRC_E(uint8_t, BGR, 8, YcCbcCrc420)
#endif

#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCCBCCRC_E(uint16_t, BGRA, 12, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint16_t, ABGR, 12, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint16_t, ARGB, 12, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint16_t, BGR, 12, YcCbcCrc444)
PIXEL_TO_YCCBCCRC_E(uint16_t, BGRA, 12, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint16_t, ABGR, 12, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint16_t, ARGB, 12, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint16_t, BGR, 12, YcCbcCrc422)
PIXEL_TO_YCCBCCRC_E(uint16_t, BGRA, 12, YcCbcCrc420)
PIXEL_TO_YCCBCCRC_E(uint16_t, ABGR, 12, YcCbcCrc420)
PIXEL_TO_YCCBCCRC_E(uint16_t, ARGB, 12, YcCbcCrc420)
PIXEL_TO_YCCBCCRC_E(uint16_t, BGR, 12, YcCbcCrc420)
#endif

#undef PIXEL_TO_YCCBCCRC_E

#define DECLARE_YCCBCCRC_TO_PX_HWY(pixel, bit, yuv) HWY_EXPORT(yuv##P##bit##To##pixel##bit##HWY);

DECLARE_YCCBCCRC_TO_PX_HWY(RGBA, 10, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(RGB, 10, YcCbcCrc444)

DECLARE_YCCBCCRC_TO_PX_HWY(RGBA, 12, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(RGB, 12, YcCbcCrc444)

DECLARE_YCCBCCRC_TO_PX_HWY(RGBA, 10, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(RGB, 10, YcCbcCrc422)

DECLARE_YCCBCCRC_TO_PX_HWY(RGBA, 12, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(RGB, 12, YcCbcCrc422)

DECLARE_YCCBCCRC_TO_PX_HWY(RGBA, 10, YcCbcCrc420)
DECLARE_YCCBCCRC_TO_PX_HWY(RGB, 10, YcCbcCrc420)

DECLARE_YCCBCCRC_TO_PX_HWY(RGBA, 12, YcCbcCrc420)
DECLARE_YCCBCCRC_TO_PX_HWY(RGB, 12, YcCbcCrc420)

DECLARE_YCCBCCRC_TO_PX_HWY(RGBA, 8, YcCbcCrc420)
DECLARE_YCCBCCRC_TO_PX_HWY(RGB, 8, YcCbcCrc420)

DECLARE_YCCBCCRC_TO_PX_HWY(RGBA, 8, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(RGB, 8, YcCbcCrc422)

DECLARE_YCCBCCRC_TO_PX_HWY(RGBA, 8, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(RGB, 8, YcCbcCrc444)

#if SPARKYUV_FULL_CHANNELS
DECLARE_YCCBCCRC_TO_PX_HWY(BGRA, 10, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(ABGR, 10, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(ARGB, 10, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(BGR, 10, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(BGRA, 10, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(ABGR, 10, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(ARGB, 10, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(BGR, 10, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(BGRA, 10, YcCbcCrc420)
DECLARE_YCCBCCRC_TO_PX_HWY(ABGR, 10, YcCbcCrc420)
DECLARE_YCCBCCRC_TO_PX_HWY(ARGB, 10, YcCbcCrc420)
DECLARE_YCCBCCRC_TO_PX_HWY(BGR, 10, YcCbcCrc420)
#endif

#if SPARKYUV_FULL_CHANNELS
DECLARE_YCCBCCRC_TO_PX_HWY(BGRA, 8, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(ABGR, 8, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(ARGB, 8, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(BGR, 8, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(BGRA, 8, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(ABGR, 8, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(ARGB, 8, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(BGR, 8, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(BGRA, 8, YcCbcCrc420)
DECLARE_YCCBCCRC_TO_PX_HWY(ABGR, 8, YcCbcCrc420)
DECLARE_YCCBCCRC_TO_PX_HWY(ARGB, 8, YcCbcCrc420)
DECLARE_YCCBCCRC_TO_PX_HWY(BGR, 8, YcCbcCrc420)
#endif

#if SPARKYUV_FULL_CHANNELS
DECLARE_YCCBCCRC_TO_PX_HWY(BGRA, 12, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(ABGR, 12, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(ARGB, 12, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(BGR, 12, YcCbcCrc444)
DECLARE_YCCBCCRC_TO_PX_HWY(BGRA, 12, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(ABGR, 12, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(ARGB, 12, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(BGR, 12, YcCbcCrc422)
DECLARE_YCCBCCRC_TO_PX_HWY(BGRA, 12, YcCbcCrc420)
DECLARE_YCCBCCRC_TO_PX_HWY(ABGR, 12, YcCbcCrc420)
DECLARE_YCCBCCRC_TO_PX_HWY(ARGB, 12, YcCbcCrc420)
DECLARE_YCCBCCRC_TO_PX_HWY(BGR, 12, YcCbcCrc420)
#endif

#undef DECLARE_YCCBCCRC_TO_PX_HWY

#define YCCBCCRC_TO_PX_DECLARATION_E(T, pixel, bit, yuv) \
    void yuv##P##bit##To##pixel##bit(T *SPARKYUV_RESTRICT src, const uint32_t srcStride,\
                                             const uint32_t width, const uint32_t height,\
                                             const T *SPARKYUV_RESTRICT yPlane, const uint32_t yStride,\
                                             const T *SPARKYUV_RESTRICT uPlane, const uint32_t uStride,\
                                             const T *SPARKYUV_RESTRICT vPlane, const uint32_t vStride,\
                                             const float kr, const float kb, const SparkYuvColorRange colorRange, \
                                             const SparkYuvTransferFunction transferFunction) {\
      HWY_DYNAMIC_DISPATCH(yuv##P##bit##To##pixel##bit##HWY)(src, srcStride, width, height,\
                                                 yPlane, yStride, uPlane, uStride, vPlane, vStride, \
                                                 kr, kb, colorRange, transferFunction);\
    }

YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, RGBA, 10, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, RGB, 10, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, RGBA, 10, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, RGB, 10, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, RGBA, 10, YcCbcCrc420)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, RGB, 10, YcCbcCrc420)

#if SPARKYUV_FULL_CHANNELS
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, BGRA, 10, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, ABGR, 10, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, ARGB, 10, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, BGR, 10, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, BGRA, 10, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, ABGR, 10, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, ARGB, 10, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, BGR, 10, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, BGRA, 10, YcCbcCrc420)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, ABGR, 10, YcCbcCrc420)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, ARGB, 10, YcCbcCrc420)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, BGR, 10, YcCbcCrc420)
#endif

YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, RGBA, 8, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, RGB, 8, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, RGBA, 8, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, RGB, 8, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, RGBA, 8, YcCbcCrc420)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, RGB, 8, YcCbcCrc420)

#if SPARKYUV_FULL_CHANNELS
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, BGRA, 8, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, ABGR, 8, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, ARGB, 8, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, BGR, 8, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, BGRA, 8, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, ABGR, 8, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, ARGB, 8, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, BGR, 8, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, BGRA, 8, YcCbcCrc420)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, ABGR, 8, YcCbcCrc420)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, ARGB, 8, YcCbcCrc420)
YCCBCCRC_TO_PX_DECLARATION_E(uint8_t, BGR, 8, YcCbcCrc420)
#endif

YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, RGBA, 12, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, RGB, 12, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, RGBA, 12, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, RGB, 12, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, RGBA, 12, YcCbcCrc420)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, RGB, 12, YcCbcCrc420)

#if SPARKYUV_FULL_CHANNELS
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, BGRA, 12, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, ABGR, 12, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, ARGB, 12, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, BGR, 12, YcCbcCrc444)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, BGRA, 12, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, ABGR, 12, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, ARGB, 12, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, BGR, 12, YcCbcCrc422)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, BGRA, 12, YcCbcCrc420)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, ABGR, 12, YcCbcCrc420)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, ARGB, 12, YcCbcCrc420)
YCCBCCRC_TO_PX_DECLARATION_E(uint16_t, BGR, 12, YcCbcCrc420)
#endif

#undef YCCBCCRC_TO_PX_DECLARATION_E

}
#endif