// Copyright (C) 2024 Radzivon Bartoshyk
//
// This file belongs to sparkyuv project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


#include "sparkyuv.h"

#undef HWY_TARGET_INCLUDE
#define HWY_TARGET_INCLUDE "src/YCgCoR.cpp"

#include "hwy/foreach_target.h"
#include "hwy/highway.h"
#include "yuv-inl.h"
#include "YCgCoR-inl.h"

#if HWY_ONCE
namespace sparkyuv {
#define DECLARE_PX_TO_YCgCoR_HWY(pixel, bit, yuv) HWY_EXPORT(pixel##bit##To##yuv##P##bit##HWY);

DECLARE_PX_TO_YCgCoR_HWY(RGBA, 10, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(RGB, 10, YCgCoR444)

DECLARE_PX_TO_YCgCoR_HWY(RGBA, 12, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(RGB, 12, YCgCoR444)

DECLARE_PX_TO_YCgCoR_HWY(RGBA, 10, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(RGB, 10, YCgCoR422)

DECLARE_PX_TO_YCgCoR_HWY(RGBA, 12, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(RGB, 12, YCgCoR422)

DECLARE_PX_TO_YCgCoR_HWY(RGBA, 10, YCgCoR420)
DECLARE_PX_TO_YCgCoR_HWY(RGB, 10, YCgCoR420)

DECLARE_PX_TO_YCgCoR_HWY(RGBA, 12, YCgCoR420)
DECLARE_PX_TO_YCgCoR_HWY(RGB, 12, YCgCoR420)

DECLARE_PX_TO_YCgCoR_HWY(RGBA, 8, YCgCoR420)
DECLARE_PX_TO_YCgCoR_HWY(RGB, 8, YCgCoR420)

DECLARE_PX_TO_YCgCoR_HWY(RGBA, 8, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(RGB, 8, YCgCoR422)

DECLARE_PX_TO_YCgCoR_HWY(RGBA, 8, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(RGB, 8, YCgCoR444)

#if SPARKYUV_FULL_CHANNELS
DECLARE_PX_TO_YCgCoR_HWY(BGRA, 10, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(ABGR, 10, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(ARGB, 10, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(BGR, 10, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(BGRA, 10, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(ABGR, 10, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(ARGB, 10, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(BGR, 10, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(BGRA, 10, YCgCoR420)
DECLARE_PX_TO_YCgCoR_HWY(ABGR, 10, YCgCoR420)
DECLARE_PX_TO_YCgCoR_HWY(ARGB, 10, YCgCoR420)
DECLARE_PX_TO_YCgCoR_HWY(BGR, 10, YCgCoR420)
#endif

#if SPARKYUV_FULL_CHANNELS
DECLARE_PX_TO_YCgCoR_HWY(BGRA, 8, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(ABGR, 8, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(ARGB, 8, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(BGR, 8, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(BGRA, 8, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(ABGR, 8, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(ARGB, 8, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(BGR, 8, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(BGRA, 8, YCgCoR420)
DECLARE_PX_TO_YCgCoR_HWY(ABGR, 8, YCgCoR420)
DECLARE_PX_TO_YCgCoR_HWY(ARGB, 8, YCgCoR420)
DECLARE_PX_TO_YCgCoR_HWY(BGR, 8, YCgCoR420)
#endif

#if SPARKYUV_FULL_CHANNELS
DECLARE_PX_TO_YCgCoR_HWY(BGRA, 12, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(ABGR, 12, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(ARGB, 12, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(BGR, 12, YCgCoR444)
DECLARE_PX_TO_YCgCoR_HWY(BGRA, 12, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(ABGR, 12, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(ARGB, 12, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(BGR, 12, YCgCoR422)
DECLARE_PX_TO_YCgCoR_HWY(BGRA, 12, YCgCoR420)
DECLARE_PX_TO_YCgCoR_HWY(ABGR, 12, YCgCoR420)
DECLARE_PX_TO_YCgCoR_HWY(ARGB, 12, YCgCoR420)
DECLARE_PX_TO_YCgCoR_HWY(BGR, 12, YCgCoR420)
#endif

#undef DECLARE_PX_TO_YCgCoR_HWY

#define PIXEL_TO_YCgCoR_E(T, PixelType, bit, yuvname) \
void PixelType##bit##To##yuvname##P##bit(const T *SPARKYUV_RESTRICT src, const uint32_t srcStride,\
                    const uint32_t width, const uint32_t height,                                 \
                    uint16_t *SPARKYUV_RESTRICT yPlane, const uint32_t yStride,                         \
                    uint16_t *SPARKYUV_RESTRICT uPlane, const uint32_t uStride,                         \
                    uint16_t *SPARKYUV_RESTRICT vPlane, const uint32_t vStride,                         \
                    const SparkYuvYCgCoRType rType) { \
      HWY_DYNAMIC_DISPATCH(PixelType##bit##To##yuvname##P##bit##HWY)(src, srcStride, width, height, \
          yPlane, yStride, uPlane, uStride, vPlane, vStride, rType);\
    }

PIXEL_TO_YCgCoR_E(uint16_t, RGBA, 10, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint16_t, RGB, 10, YCgCoR444)

PIXEL_TO_YCgCoR_E(uint16_t, RGBA, 12, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint16_t, RGB, 12, YCgCoR444)

PIXEL_TO_YCgCoR_E(uint16_t, RGBA, 10, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint16_t, RGB, 10, YCgCoR422)

PIXEL_TO_YCgCoR_E(uint16_t, RGBA, 12, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint16_t, RGB, 12, YCgCoR422)

PIXEL_TO_YCgCoR_E(uint16_t, RGBA, 10, YCgCoR420)
PIXEL_TO_YCgCoR_E(uint16_t, RGB, 10, YCgCoR420)

PIXEL_TO_YCgCoR_E(uint16_t, RGBA, 12, YCgCoR420)
PIXEL_TO_YCgCoR_E(uint16_t, RGB, 12, YCgCoR420)

PIXEL_TO_YCgCoR_E(uint8_t, RGBA, 8, YCgCoR420)
PIXEL_TO_YCgCoR_E(uint8_t, RGB, 8, YCgCoR420)

PIXEL_TO_YCgCoR_E(uint8_t, RGBA, 8, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint8_t, RGB, 8, YCgCoR422)

PIXEL_TO_YCgCoR_E(uint8_t, RGBA, 8, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint8_t, RGB, 8, YCgCoR444)

#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCgCoR_E(uint16_t, BGRA, 10, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint16_t, ABGR, 10, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint16_t, ARGB, 10, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint16_t, BGR, 10, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint16_t, BGRA, 10, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint16_t, ABGR, 10, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint16_t, ARGB, 10, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint16_t, BGR, 10, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint16_t, BGRA, 10, YCgCoR420)
PIXEL_TO_YCgCoR_E(uint16_t, ABGR, 10, YCgCoR420)
PIXEL_TO_YCgCoR_E(uint16_t, ARGB, 10, YCgCoR420)
PIXEL_TO_YCgCoR_E(uint16_t, BGR, 10, YCgCoR420)
#endif

#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCgCoR_E(uint8_t, BGRA, 8, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint8_t, ABGR, 8, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint8_t, ARGB, 8, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint8_t, BGR, 8, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint8_t, BGRA, 8, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint8_t, ABGR, 8, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint8_t, ARGB, 8, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint8_t, BGR, 8, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint8_t, BGRA, 8, YCgCoR420)
PIXEL_TO_YCgCoR_E(uint8_t, ABGR, 8, YCgCoR420)
PIXEL_TO_YCgCoR_E(uint8_t, ARGB, 8, YCgCoR420)
PIXEL_TO_YCgCoR_E(uint8_t, BGR, 8, YCgCoR420)
#endif

#if SPARKYUV_FULL_CHANNELS
PIXEL_TO_YCgCoR_E(uint16_t, BGRA, 12, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint16_t, ABGR, 12, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint16_t, ARGB, 12, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint16_t, BGR, 12, YCgCoR444)
PIXEL_TO_YCgCoR_E(uint16_t, BGRA, 12, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint16_t, ABGR, 12, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint16_t, ARGB, 12, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint16_t, BGR, 12, YCgCoR422)
PIXEL_TO_YCgCoR_E(uint16_t, BGRA, 12, YCgCoR420)
PIXEL_TO_YCgCoR_E(uint16_t, ABGR, 12, YCgCoR420)
PIXEL_TO_YCgCoR_E(uint16_t, ARGB, 12, YCgCoR420)
PIXEL_TO_YCgCoR_E(uint16_t, BGR, 12, YCgCoR420)
#endif

#undef PIXEL_TO_YCgCoR_E

#define DECLARE_YCgCoR_TO_PX_HWY(pixel, bit, yuv) HWY_EXPORT(yuv##P##bit##To##pixel##bit##HWY);

DECLARE_YCgCoR_TO_PX_HWY(RGBA, 10, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(RGB, 10, YCgCoR444)

DECLARE_YCgCoR_TO_PX_HWY(RGBA, 12, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(RGB, 12, YCgCoR444)

DECLARE_YCgCoR_TO_PX_HWY(RGBA, 10, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(RGB, 10, YCgCoR422)

DECLARE_YCgCoR_TO_PX_HWY(RGBA, 12, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(RGB, 12, YCgCoR422)

DECLARE_YCgCoR_TO_PX_HWY(RGBA, 10, YCgCoR420)
DECLARE_YCgCoR_TO_PX_HWY(RGB, 10, YCgCoR420)

DECLARE_YCgCoR_TO_PX_HWY(RGBA, 12, YCgCoR420)
DECLARE_YCgCoR_TO_PX_HWY(RGB, 12, YCgCoR420)

DECLARE_YCgCoR_TO_PX_HWY(RGBA, 8, YCgCoR420)
DECLARE_YCgCoR_TO_PX_HWY(RGB, 8, YCgCoR420)

DECLARE_YCgCoR_TO_PX_HWY(RGBA, 8, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(RGB, 8, YCgCoR422)

DECLARE_YCgCoR_TO_PX_HWY(RGBA, 8, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(RGB, 8, YCgCoR444)

#if SPARKYUV_FULL_CHANNELS
DECLARE_YCgCoR_TO_PX_HWY(BGRA, 10, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(ABGR, 10, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(ARGB, 10, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(BGR, 10, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(BGRA, 10, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(ABGR, 10, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(ARGB, 10, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(BGR, 10, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(BGRA, 10, YCgCoR420)
DECLARE_YCgCoR_TO_PX_HWY(ABGR, 10, YCgCoR420)
DECLARE_YCgCoR_TO_PX_HWY(ARGB, 10, YCgCoR420)
DECLARE_YCgCoR_TO_PX_HWY(BGR, 10, YCgCoR420)
#endif

#if SPARKYUV_FULL_CHANNELS
DECLARE_YCgCoR_TO_PX_HWY(BGRA, 8, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(ABGR, 8, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(ARGB, 8, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(BGR, 8, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(BGRA, 8, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(ABGR, 8, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(ARGB, 8, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(BGR, 8, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(BGRA, 8, YCgCoR420)
DECLARE_YCgCoR_TO_PX_HWY(ABGR, 8, YCgCoR420)
DECLARE_YCgCoR_TO_PX_HWY(ARGB, 8, YCgCoR420)
DECLARE_YCgCoR_TO_PX_HWY(BGR, 8, YCgCoR420)
#endif

#if SPARKYUV_FULL_CHANNELS
DECLARE_YCgCoR_TO_PX_HWY(BGRA, 12, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(ABGR, 12, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(ARGB, 12, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(BGR, 12, YCgCoR444)
DECLARE_YCgCoR_TO_PX_HWY(BGRA, 12, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(ABGR, 12, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(ARGB, 12, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(BGR, 12, YCgCoR422)
DECLARE_YCgCoR_TO_PX_HWY(BGRA, 12, YCgCoR420)
DECLARE_YCgCoR_TO_PX_HWY(ABGR, 12, YCgCoR420)
DECLARE_YCgCoR_TO_PX_HWY(ARGB, 12, YCgCoR420)
DECLARE_YCgCoR_TO_PX_HWY(BGR, 12, YCgCoR420)
#endif

#undef DECLARE_YCgCoR_TO_PX_HWY

#define YCgCoR_TO_PX_DECLARATION_E(T, pixel, bit, yuv) \
    void yuv##P##bit##To##pixel##bit(T *SPARKYUV_RESTRICT src, const uint32_t srcStride,\
                                             const uint32_t width, const uint32_t height,\
                                             const uint16_t *SPARKYUV_RESTRICT yPlane, const uint32_t yStride,\
                                             const uint16_t *SPARKYUV_RESTRICT uPlane, const uint32_t uStride,\
                                             const uint16_t *SPARKYUV_RESTRICT vPlane, const uint32_t vStride,\
                                             const SparkYuvYCgCoRType rType) {\
      HWY_DYNAMIC_DISPATCH(yuv##P##bit##To##pixel##bit##HWY)(src, srcStride, width, height,\
                                                 yPlane, yStride, uPlane, uStride, vPlane, vStride, \
                                                 rType);\
    }

YCgCoR_TO_PX_DECLARATION_E(uint16_t, RGBA, 10, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, RGB, 10, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, RGBA, 10, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, RGB, 10, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, RGBA, 10, YCgCoR420)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, RGB, 10, YCgCoR420)

#if SPARKYUV_FULL_CHANNELS
YCgCoR_TO_PX_DECLARATION_E(uint16_t, BGRA, 10, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, ABGR, 10, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, ARGB, 10, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, BGR, 10, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, BGRA, 10, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, ABGR, 10, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, ARGB, 10, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, BGR, 10, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, BGRA, 10, YCgCoR420)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, ABGR, 10, YCgCoR420)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, ARGB, 10, YCgCoR420)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, BGR, 10, YCgCoR420)
#endif

YCgCoR_TO_PX_DECLARATION_E(uint8_t, RGBA, 8, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, RGB, 8, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, RGBA, 8, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, RGB, 8, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, RGBA, 8, YCgCoR420)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, RGB, 8, YCgCoR420)

#if SPARKYUV_FULL_CHANNELS
YCgCoR_TO_PX_DECLARATION_E(uint8_t, BGRA, 8, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, ABGR, 8, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, ARGB, 8, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, BGR, 8, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, BGRA, 8, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, ABGR, 8, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, ARGB, 8, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, BGR, 8, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, BGRA, 8, YCgCoR420)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, ABGR, 8, YCgCoR420)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, ARGB, 8, YCgCoR420)
YCgCoR_TO_PX_DECLARATION_E(uint8_t, BGR, 8, YCgCoR420)
#endif

YCgCoR_TO_PX_DECLARATION_E(uint16_t, RGBA, 12, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, RGB, 12, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, RGBA, 12, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, RGB, 12, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, RGBA, 12, YCgCoR420)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, RGB, 12, YCgCoR420)

#if SPARKYUV_FULL_CHANNELS
YCgCoR_TO_PX_DECLARATION_E(uint16_t, BGRA, 12, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, ABGR, 12, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, ARGB, 12, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, BGR, 12, YCgCoR444)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, BGRA, 12, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, ABGR, 12, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, ARGB, 12, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, BGR, 12, YCgCoR422)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, BGRA, 12, YCgCoR420)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, ABGR, 12, YCgCoR420)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, ARGB, 12, YCgCoR420)
YCgCoR_TO_PX_DECLARATION_E(uint16_t, BGR, 12, YCgCoR420)
#endif

#undef YCgCoR_TO_PX_DECLARATION_E

}
#endif