# https://github.com/marketplace/actions/run-on-architecture
name: Foreign architectures

on:
  push:
    branches:
      - none
  pull_request:
    branches:
      - none

# [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  multiarch:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu_latest
            cxx_flags: -Wno-psabi
          - arch: ppc64le
            distro: ubuntu_latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and test
        uses: uraimo/run-on-arch-action@v2.7.1
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          # Not required, but speeds up builds
          githubToken: ${{ github.token }}
          env: |
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          install: |
            apt-get update -q -y
            apt-get install -q -y --no-install-recommends \
                  build-essential \
                  cmake \
                  ninja-build \
                  git \
                  ;
          run: |
            export GIT_SSL_NO_VERIFY=1
            git config --global http.sslverify false
            git clone --branch widen_mul https://token:${GITHUB_TOKEN}@github.com/awxkee/highway
            export CMAKE_BUILD_PARALLEL_LEVEL=2
            export CTEST_PARALLEL_LEVEL=2
            CXXFLAGS=${{ matrix.cxx_flags }} cmake -GNinja ${{ matrix.cmake_flags }} -B out .
            cmake --build out
            ctest --test-dir out