permissions: read-all

name: Build x86_64 Windows

on:
  push:
    branches:
      - '*'
#      - '!ci_test_*'
  pull_request:
    branches:
      - '*'
#      - '!ci_test_*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake_windows:
    name: Build x86_64 Windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
        build_type: [Release]
        c_compiler: [cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.0.0

      - name: Build and test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone --branch widen_mul https://token:${GITHUB_TOKEN}@github.com/awxkee/highway
          cmake -DCMAKE_BUILD_TYPE=Release -B out .
          cmake --build out
          ctest --test-dir out